### ISSUE TITLE
[Feature request]: Vision and Roadmap Documentation

### ISSUE THREAD

**Issue by aiAdrian** [SchweizerischeBundesbahnen/netzgrafik-editor-frontend#66]
### Preflight Checklist

- [ ] I have read the [Contributing Guidelines](https://github.com/SchweizerischeBundesbahnen/netzgrafik-editor-frontend/blob/main/CONTRIBUTING.md) for this project.
- [ ] I agree to follow the [Code of Conduct](https://github.com/SchweizerischeBundesbahnen/netzgrafik-editor-frontend/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [ ] I have searched the [issue tracker](https://github.com/orgs/sbb-design-systems/projects/1) for an issue that matches the one I want to file, without success.

### Request type

None

### Functionality

The vision and the roadmap need to be documented somewhere in the repository.
